name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:conformance"
          push: true
          tags: ghcr.io/silvanoc/distribution-spec:latest
      -
        name: Build and push debug
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:conformance"
          target: debug
          push: true
          tags: ghcr.io/silvanoc/distribution-spec:debug
